services:
  # Our PostgreSQL dataset
  db:
    # THe Docker image of postgres -- we're using the latest
    image: postgres:latest
    # The parts to expose to the host container
    # 5432 is the default PostgreSQL part
    ports:
      - "5432:5432"
    # If we accidentally kill the running container, Docker Compose
    # will restart it.
    restart: always
    # The PostgreSQL  Docker container uses enivronment variable to
    # read configuration, here we set the password.
    # - Do not store plaintext passwords in source control. We
    # - do so here as this is a builder.
    environment:
      POSTGRES_PASSWORD: changemeinprod!